---
abstract: 'Perl interface to interact with the Codeguard API'
author:
  - 'Rishwanth Yeddula <ryeddula@cpan.org>'
  - 'David Oswald <davido@cpan.org>'
  - 'James Jacobson <shames@cpan.org>'
build_requires:
  JSON: '0'
  Test::MockModule: '0'
  Test::More: '0'
  parent: '0'
configure_requires:
  ExtUtils::MakeMaker: '7.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Codeguard
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Net::OAuth: '0'
  parent: '0'
  perl: '5.008009'
resources:
  repository: https://github.com/daoswald/www-codeguard.git
version: '0.10'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
