---
abstract: 'Perl interface to interact with the Codeguard API'
author:
  - 'Rishwanth Yeddula <ryeddula@cpan.org>'
build_requires:
  JSON: '0'
  Test::More: '0'
  parent: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Codeguard
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Net::OAuth: '0'
  parent: '0'
  perl: '5.006'
resources:
  repository: https://github.com/ryeddula/www-codeguard.git
version: '0.03'
